<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Chameleon.app.Playwright</RootNamespace>
		<AssemblyTitle>Chameleon.app.Playwright</AssemblyTitle>
		<Description>Chameleon.app.Playwright for chameleonmode</Description>
		<Configuration></Configuration>
		<Company></Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>Chameleon.app.Playwright$(PackageSuffix)</PackageId>
		<Configurations>Debug;Release;ReleaseAvalonia;ReleaseWPF;ReleaseAvaloniaRemoteDebugSupport</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>


	<ItemGroup>
		    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
		    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
			  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
			  <PackageReference Include="Microsoft.Extensions.Logging.Console" />
	  <PackageReference Include="Microsoft.Playwright" />
	  <PackageReference Include="System.Text.Json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\chameleon-lib\Chameleon.lib\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
		<ProjectReference Include="..\..\..\..\chameleon-lib\Chameleon.lib\Chameleon.lib.Core\Chameleon.lib.Core.csproj" />
	  </ItemGroup>

</Project>
